<?php
namespace App\Services;
use App\Models\ModuleSubscription;use App\Models\SubscriptionOrder;use Illuminate\Support\Carbon;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Http;use RuntimeException;
class PaystackService {
 private function secret():string{$key=(string)config('services.paystack.secret_key');if($key==='')throw new RuntimeException('Paystack is not configured. Add PAYSTACK_SECRET_KEY to the backend environment.');return $key;}
 public function initialize(SubscriptionOrder $order,string $email):array{$response=Http::withToken($this->secret())->acceptJson()->post('https://api.paystack.co/transaction/initialize',['email'=>$email,'amount'=>(string)$order->amount_kobo,'currency'=>'NGN','reference'=>$order->reference,'callback_url'=>route('subscriptions.callback'),'metadata'=>['order_id'=>$order->id,'organization_id'=>$order->organization_id]]);$data=$response->throw()->json('data')??[];if(empty($data['access_code'])||empty($data['authorization_url']))throw new RuntimeException('Paystack did not return checkout credentials.');return $data;}
 public function verify(string $reference):array{return Http::withToken($this->secret())->acceptJson()->get('https://api.paystack.co/transaction/verify/'.urlencode($reference))->throw()->json('data')??[];}
 public function fulfill(SubscriptionOrder $order,array $payment):bool {if(($payment['status']??null)!=='success'||(int)($payment['amount']??0)!==$order->amount_kobo||($payment['currency']??'')!=='NGN'||($payment['reference']??'')!==$order->reference)return false;DB::transaction(function()use($order,$payment){$locked=SubscriptionOrder::lockForUpdate()->findOrFail($order->id);if($locked->status==='paid')return;$now=now();foreach($locked->items as $item){$moduleId=DB::table('modules')->where('code',$item['code'])->value('id');if(!$moduleId)continue;$current=DB::table('organization_modules')->where('organization_id',$locked->organization_id)->where('module_id',$moduleId)->value('expires_at');$expiry=$current?Carbon::parse($current):null;$periodStart=$expiry?->isFuture()?$expiry:$now->copy();$expires=$item['cycle']==='yearly'?$periodStart->copy()->addYear():$periodStart->copy()->addMonth();ModuleSubscription::create(['organization_id'=>$locked->organization_id,'module_id'=>$moduleId,'subscription_order_id'=>$locked->id,'billing_cycle'=>$item['cycle'],'amount_kobo'=>$item['amount_kobo'],'status'=>'active','starts_at'=>$now,'expires_at'=>$expires]);DB::table('organization_modules')->updateOrInsert(['organization_id'=>$locked->organization_id,'module_id'=>$moduleId],['enabled'=>true,'starts_at'=>$now,'expires_at'=>$expires]);}$locked->update(['status'=>'paid','paystack_transaction_id'=>(string)($payment['id']??''),'paid_at'=>$now]);});return true;}
}
