import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, ReactNode, useMemo, useState } from 'react';

type Row = Record<string, string | number | boolean | null>;
type Option = { id:number; name?:string; first_name?:string; last_name?:string; class?:string; organization_id?:number };
type Props = { section:string; config:{title:string;description:string;action:string}; records:Row[]; summary:{visitors:number;students:number;vehicles:number;activeIncidents:number}; isSuperAdmin:boolean; canCreate:boolean; options:{organizations:Option[];visitors:Option[];students:Option[]}; flash?:{success?:string;error?:string} };
const labels:Record<string,string>={first_name:'First name',last_name:'Last name',student_first_name:'Student',student_last_name:'Student surname',pickup_first_name:'Pickup person',pickup_last_name:'Pickup surname',registration_number:'Registration',driver_name:'Driver',last_seen_at:'Last seen',created_at:'Created',valid_until:'Valid until',invitation_code:'Pass code',authorization_code:'Authorization code',entity_type:'Record type',entity_id:'Record ID',ip_address:'IP address',location_name:'Location'};
const routes:Record<string,string>={organizations:'/portal/organizations',people:'/portal/people',visitors:'/portal/visitors',invitations:'/portal/invitations','entry-exit':'/portal/entry-exit/verify',students:'/portal/students',pickup:'/portal/pickup'};
const Field=({label,children}:{label:string;children:ReactNode})=><label>{label}{children}</label>;

export default function PortalIndex({section,config,records,summary,isSuperAdmin,canCreate,options,flash}:Props){
 const [query,setQuery]=useState(''); const [modal,setModal]=useState(false);
 const now=new Date(), tomorrow=new Date(now.getTime()+86400000); const local=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
 const form=useForm({organization_id:'',name:'',type:'school',admin_name:'',admin_email:'',email:'',phone:'',role:'staff',password:'',first_name:'',last_name:'',visitor_id:'',purpose:'',valid_from:local(now),valid_until:local(tomorrow),entry_type:'single',maximum_entries:'1',student_number:'',class:'',student_id:'',relationship:'',authorization_type:'one_time',token:''});
 const vehicle=useForm({name:'',registration_number:'',device_uid:'',driver_name:''}); const panic=useForm({location_name:'Main Gate',message:''});
 const rows=useMemo(()=>records.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[records,query]);
 const columns=Object.keys(records[0]??{name:'',status:'',created_at:''}).filter(k=>k!=='id'&&k!=='uuid').slice(0,7);
 const action=()=>{if(section==='reports'||section==='audit-logs'){const csv=[columns.join(','),...rows.map(r=>columns.map(c=>JSON.stringify(r[c]??'')).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`nemtrack-${section}.csv`;a.click();URL.revokeObjectURL(a.href);}else{form.clearErrors();setModal(true)}};
 const submit=(e:FormEvent)=>{e.preventDefault();if(section==='vts')vehicle.post('/portal/vts/vehicles',{onSuccess:()=>{setModal(false);vehicle.reset()}});else if(section==='pbs')panic.post('/portal/pbs/incidents',{onSuccess:()=>{setModal(false);panic.reset()}});else if(routes[section])form.post(routes[section],{onSuccess:()=>{setModal(false);form.reset()}})};
 const orgSelect=isSuperAdmin&&section!=='organizations'?<Field label="Organization"><select required value={form.data.organization_id} onChange={e=>form.setData('organization_id',e.target.value)}><option value="">Select organization</option>{options.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>:null;
 const orgName=(id?:number)=>options.organizations.find(o=>o.id===id)?.name??'';
 const fields=()=>{switch(section){
  case'organizations':return <><Field label="Organization name"><input required value={form.data.name} onChange={e=>form.setData('name',e.target.value)} placeholder="Greenfield Academy"/></Field><Field label="Organization type"><select value={form.data.type} onChange={e=>form.setData('type',e.target.value)}>{['school','estate','company','hospital','church','hotel','government','event','industrial'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></Field><Field label="Administrator name"><input required value={form.data.admin_name} onChange={e=>form.setData('admin_name',e.target.value)}/></Field><Field label="Administrator email"><input required type="email" value={form.data.admin_email} onChange={e=>form.setData('admin_email',e.target.value)}/></Field></>;
  case'people':return <>{orgSelect}<Field label="Full name"><input required value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/></Field><Field label="Email"><input required type="email" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/></Field><Field label="Phone"><input value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)}/></Field><Field label="Role"><select value={form.data.role} onChange={e=>form.setData('role',e.target.value)}>{['staff','security_officer','parent','guardian','resident','organization_admin'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></Field><Field label="Temporary password"><input required minLength={8} type="password" value={form.data.password} onChange={e=>form.setData('password',e.target.value)}/></Field></>;
  case'visitors':return <>{orgSelect}<Field label="First name"><input required value={form.data.first_name} onChange={e=>form.setData('first_name',e.target.value)}/></Field><Field label="Last name"><input required value={form.data.last_name} onChange={e=>form.setData('last_name',e.target.value)}/></Field><Field label="Phone"><input required value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)}/></Field><Field label="Email"><input type="email" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/></Field></>;
  case'invitations':return <><Field label="Visitor"><select required value={form.data.visitor_id} onChange={e=>form.setData('visitor_id',e.target.value)}><option value="">Select visitor</option>{options.visitors.map(v=><option key={v.id} value={v.id}>{v.first_name} {v.last_name}{isSuperAdmin?` · ${orgName(v.organization_id)}`:''}</option>)}</select></Field><Field label="Purpose"><input required value={form.data.purpose} onChange={e=>form.setData('purpose',e.target.value)}/></Field><Field label="Valid from"><input required type="datetime-local" value={form.data.valid_from} onChange={e=>form.setData('valid_from',e.target.value)}/></Field><Field label="Valid until"><input required type="datetime-local" value={form.data.valid_until} onChange={e=>form.setData('valid_until',e.target.value)}/></Field><Field label="Entry type"><select value={form.data.entry_type} onChange={e=>form.setData('entry_type',e.target.value)}><option value="single">Single entry</option><option value="multiple">Multiple entry</option><option value="recurring">Recurring</option></select></Field><Field label="Maximum entries"><input required type="number" min="1" max="100" value={form.data.maximum_entries} onChange={e=>form.setData('maximum_entries',e.target.value)}/></Field></>;
  case'entry-exit':return <><div className="form-note">Enter the pass code or paste its QR token to verify access.</div><Field label="Pass code or QR token"><input autoFocus required value={form.data.token} onChange={e=>form.setData('token',e.target.value)} placeholder="NMT123"/></Field></>;
  case'students':return <>{orgSelect}<Field label="Student number"><input required value={form.data.student_number} onChange={e=>form.setData('student_number',e.target.value)}/></Field><Field label="First name"><input required value={form.data.first_name} onChange={e=>form.setData('first_name',e.target.value)}/></Field><Field label="Last name"><input required value={form.data.last_name} onChange={e=>form.setData('last_name',e.target.value)}/></Field><Field label="Class"><input required value={form.data.class} onChange={e=>form.setData('class',e.target.value)}/></Field></>;
  case'pickup':return <><Field label="Student"><select required value={form.data.student_id} onChange={e=>form.setData('student_id',e.target.value)}><option value="">Select student</option>{options.students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.class}{isSuperAdmin?` · ${orgName(s.organization_id)}`:''}</option>)}</select></Field><Field label="Pickup person first name"><input required value={form.data.first_name} onChange={e=>form.setData('first_name',e.target.value)}/></Field><Field label="Pickup person last name"><input required value={form.data.last_name} onChange={e=>form.setData('last_name',e.target.value)}/></Field><Field label="Phone"><input required value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)}/></Field><Field label="Relationship"><input required value={form.data.relationship} onChange={e=>form.setData('relationship',e.target.value)}/></Field><Field label="Authorization type"><select value={form.data.authorization_type} onChange={e=>form.setData('authorization_type',e.target.value)}>{['one_time','temporary','permanent','emergency'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></Field><Field label="Valid until"><input required type="datetime-local" value={form.data.valid_until} onChange={e=>form.setData('valid_until',e.target.value)}/></Field></>;
  case'vts':return <><Field label="Vehicle name"><input required value={vehicle.data.name} onChange={e=>vehicle.setData('name',e.target.value)}/></Field><Field label="Registration number"><input required value={vehicle.data.registration_number} onChange={e=>vehicle.setData('registration_number',e.target.value)}/></Field><Field label="Tracking device UID"><input required value={vehicle.data.device_uid} onChange={e=>vehicle.setData('device_uid',e.target.value)}/></Field><Field label="Driver"><input value={vehicle.data.driver_name} onChange={e=>vehicle.setData('driver_name',e.target.value)}/></Field></>;
  case'pbs':return <><div className="panic-warning">This immediately creates a critical incident visible to security operators.</div><Field label="Emergency location"><input required value={panic.data.location_name} onChange={e=>panic.setData('location_name',e.target.value)}/></Field><Field label="Message"><textarea value={panic.data.message} onChange={e=>panic.setData('message',e.target.value)}/></Field></>;
 }};
 const error=Object.values(form.errors)[0]||Object.values(vehicle.errors)[0]||Object.values(panic.errors)[0];
 return <AuthenticatedLayout><Head title={config.title}/>{flash?.success&&<div className="flash-banner success">✓ {flash.success}</div>}{flash?.error&&<div className="flash-banner error">! {flash.error}</div>}
 <section className="portal-heading"><div><span>NEMTRACK PORTAL</span><h1>{config.title}</h1><p>{config.description}</p></div>{canCreate&&<button className={section==='pbs'?'danger-action':'btn-primary'} onClick={action}>{section==='pbs'?'⚠ ':'＋ '}{config.action}</button>}</section>
 <section className="mini-stats"><div><span>VISITORS</span><b>{summary.visitors}</b></div><div><span>STUDENTS</span><b>{summary.students}</b></div><div><span>TRACKED VEHICLES</span><b>{summary.vehicles}</b></div><div><span>ACTIVE EMERGENCIES</span><b className={summary.activeIncidents?'danger-text':''}>{summary.activeIncidents}</b></div></section>
 <section className="data-panel"><header><div><h3>{config.title}</h3><p>{rows.length} records in this workspace</p></div><div className="table-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records..."/></div></header>{rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{labels[c]??c.replaceAll('_',' ')}</th>)}{section==='pbs'&&<th>Response</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)}>{columns.map(c=><td key={c}>{c==='status'?<span className={`record-status ${row[c]}`}>{String(row[c])}</span>:c.includes('_at')||c==='created_at'?row[c]?new Date(String(row[c])).toLocaleString():'—':typeof row[c]==='boolean'?(row[c]?'Yes':'No'):String(row[c]??'—')}</td>)}{section==='pbs'&&<td>{row.status==='active'?<button className="table-action" onClick={()=>router.patch(`/portal/pbs/incidents/${row.id}`,{status:'acknowledged'})}>Acknowledge</button>:row.status==='acknowledged'?<button className="table-action" onClick={()=>router.patch(`/portal/pbs/incidents/${row.id}`,{status:'resolved'})}>Resolve</button>:'Completed'}</td>}</tr>)}</tbody></table></div>:<div className="empty-state"><span>◇</span><h3>No records yet</h3><p>Use “{config.action}” to begin managing this workspace.</p></div>}</section>
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="portal-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><span>{section==='pbs'?'EMERGENCY RESPONSE':'NEW RECORD'}</span><h2>{config.action}</h2></div><button type="button" onClick={()=>setModal(false)}>×</button></header><div className="portal-form-body">{fields()}{error&&<div className="form-error">{error}</div>}</div><footer><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className={section==='pbs'?'danger-action':'btn-primary'} disabled={form.processing||vehicle.processing||panic.processing}>{section==='pbs'?'Activate emergency':section==='entry-exit'?'Verify pass':config.action}</button></footer></form></div>}
 </AuthenticatedLayout>;
}
