import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { PageProps } from '@/types';
import { FormEvent } from 'react';

type Props={stats:{organizations:number;administrators:number;users:number;activeIncidents:number;visitors:number;vehicles:number};activity:Array<{id:number;administrator:string|null;organization:string|null;action:string;created_at:string}>;organizations:Array<{id:number;name:string;type:string;status:string;administrators:number}>;mapboxConfigured:boolean};
export default function SuperAdminDashboard({stats,activity,organizations,mapboxConfigured}:Props){
 const user=usePage<PageProps>().props.auth.user;const firstName=user.name.split(/\s+/)[0];const mapbox=useForm({mapbox_access_token:''});
 const saveMapbox=(event:FormEvent)=>{event.preventDefault();mapbox.put('/platform/settings/mapbox',{preserveScroll:true,onSuccess:()=>mapbox.reset()});};
 return <AuthenticatedLayout><Head title="Platform command centre"/>
  <section className="welcome-row"><div><p>PLATFORM CONTROL</p><h1>Welcome back, {firstName}.</h1><span>Global visibility across every NEMTRACK organization and administrator.</span></div><div className="welcome-actions"><Link className="btn-secondary" href="/portal/audit-logs">Review audit trail</Link><Link className="btn-primary" href="/portal/organizations">＋ Manage organizations</Link></div></section>
  <section className="super-alert"><div><span>◆</span><div><b>Platform oversight active</b><p>All tenant activity is visible and isolated. Critical actions are being audited.</p></div></div><Link href="/portal/pbs"><em>{stats.activeIncidents} ACTIVE INCIDENTS →</em></Link></section>
  <section className="super-stats"><article><span className="blue">▦</span><div><small>ORGANIZATIONS</small><b>{stats.organizations}</b><p>Active tenant workspaces</p></div></article><article><span className="violet">♙</span><div><small>ADMINISTRATORS</small><b>{stats.administrators}</b><p>Organization administrators</p></div></article><article><span className="aqua">◎</span><div><small>PLATFORM USERS</small><b>{stats.users}</b><p>Across all organizations</p></div></article><article><span className="orange">!</span><div><small>ACTIVE EMERGENCIES</small><b>{stats.activeIncidents}</b><p>Requiring attention</p></div></article></section>
  <section className="panel mapbox-settings"><header><div><h3>Mapbox configuration</h3><p>Securely provide the public map token used by authenticated NEMTRACK apps.</p></div><span className={`record-status ${mapboxConfigured?'active':'offline'}`}>{mapboxConfigured?'Configured':'Not configured'}</span></header><form onSubmit={saveMapbox}><label>Public access token<input type="password" autoComplete="off" value={mapbox.data.mapbox_access_token} onChange={e=>mapbox.setData('mapbox_access_token',e.target.value)} placeholder={mapboxConfigured?'Enter a new pk. token to replace the current token':'pk.eyJ1...'} required/></label><button className="btn-primary" disabled={mapbox.processing}>Save Mapbox token</button>{mapbox.errors.mapbox_access_token&&<small>{mapbox.errors.mapbox_access_token}</small>}</form><p className="setting-note">Only public tokens beginning with <b>pk.</b> are accepted. The stored value is encrypted and is never displayed again.</p></section>
  <section className="dashboard-grid"><article className="panel platform-activity"><header><div><h3>Administrator activity</h3><p>Actions performed across every tenant</p></div><Link href="/portal/audit-logs">View complete audit →</Link></header>{activity.length?<div>{activity.map(item=><div className="admin-event" key={item.id}><span>{(item.administrator??'System').slice(0,1)}</span><div><b>{item.administrator??'System process'}</b><p>{item.action.replaceAll('.',' ')} · {item.organization??'Platform'}</p></div><time>{new Date(item.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>)}</div>:<div className="empty-admin">No administrator actions recorded yet.</div>}</article><article className="panel"><header><div><h3>Platform coverage</h3><p>Live operational totals</p></div></header><div className="coverage-grid"><Link href="/portal/visitors"><b>{stats.visitors}</b><span>Total visitors</span></Link><Link href="/portal/vts"><b>{stats.vehicles}</b><span>Tracked vehicles</span></Link><Link href="/portal/people"><b>{stats.users}</b><span>Managed users</span></Link><Link href="/portal/pbs"><b>{stats.activeIncidents}</b><span>Open incidents</span></Link></div></article></section>
  <section className="panel organizations-panel"><header><div><h3>Organizations</h3><p>Tenant status and administrative coverage</p></div><Link href="/portal/organizations">Manage all →</Link></header><div className="org-list">{organizations.map(org=><Link href="/portal/organizations" key={org.id}><span>{org.name.slice(0,2).toUpperCase()}</span><div><b>{org.name}</b><small>{org.type} · {org.administrators} administrator(s)</small></div><em className={`record-status ${org.status}`}>{org.status}</em></Link>)}</div></section>
 </AuthenticatedLayout>;
}
