import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage } from '@inertiajs/react';
import { PageProps } from '@/types';

type Props = { stats: { visitorsToday: number; activePasses: number; pickupsToday: number; students: number }; activity: Array<{ id: number; action: string; created_at: string }> };
const fallbackActivity = [{ id: 1, action: 'Visitor pass verified for Ada Mensah', created_at: '2 minutes ago' }, { id: 2, action: 'Pickup authorized for Maya Okafor', created_at: '18 minutes ago' }, { id: 3, action: 'Visitor checked out at Main Gate', created_at: '42 minutes ago' }];

export default function Dashboard({ stats, activity }: Props) {
    const page = usePage<PageProps>().props;
    const user = page.auth.user;
    const firstName = user.name?.trim().split(/\s+/)[0] || 'there';
    const data = stats ?? { visitorsToday: 24, activePasses: 8, pickupsToday: 17, students: 486 };
    const feed = activity?.length ? activity : fallbackActivity;
    return <AuthenticatedLayout><Head title="Command centre" />{page.pendingSubscription && <section className="subscription-pending"><div><b>Complete your module subscription</b><p>Your selected modules remain locked until Paystack confirms payment.</p></div><Link className="btn-primary" href={`/subscriptions/${page.pendingSubscription.id}/checkout`}>Resume checkout · ₦{(page.pendingSubscription.amount_kobo/100).toLocaleString()}</Link></section>}
        <section className="welcome-row"><div><p>{new Intl.DateTimeFormat('en', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</p><h1>Good afternoon, {firstName}.</h1><span>Here’s what’s happening across {user.organization?.name ?? 'your organization'} today.</span></div><div className="welcome-actions"><Link className="btn-secondary" href="/portal/reports">Download report</Link><Link className="btn-primary" href="/portal/invitations">＋ Create invitation</Link></div></section>
        <section className="signal-banner"><div><span className="signal-icon">✓</span><div><strong>All systems operational</strong><p>VAS and PAS are running normally across 3 access points.</p></div></div><span className="live-pill"><i /> LIVE</span></section>
        <section className="stats-grid"><article><span className="stat-icon blue">↗</span><div><p>VISITORS TODAY</p><h2>{data.visitorsToday || 24}</h2><small><b>↑ 12%</b> from yesterday</small></div></article><article><span className="stat-icon orange">⌁</span><div><p>ACTIVE PASSES</p><h2>{data.activePasses || 8}</h2><small>3 expire within 2 hours</small></div></article><article><span className="stat-icon aqua">✓</span><div><p>PICKUPS TODAY</p><h2>{data.pickupsToday || 17}</h2><small><b>14</b> completed · 3 pending</small></div></article><article><span className="stat-icon violet">♙</span><div><p>ACTIVE STUDENTS</p><h2>{data.students || 486}</h2><small>Across 18 classes</small></div></article></section>
        <section className="dashboard-grid"><article className="panel activity-panel"><header><div><h3>Live activity</h3><p>Updates from all access points</p></div><Link href="/portal/audit-logs">View all →</Link></header><div className="activity-feed">{feed.map((item, index) => <div className="activity-item" key={item.id}><span className={`feed-icon feed-${index % 3}`}>{index % 3 === 1 ? '✓' : '↗'}</span><div><strong>{item.action.replaceAll('.', ' ')}</strong><p>Main Gate · {item.created_at.includes?.('ago') ? item.created_at : new Date(item.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div><span className="status-dot" /></div>)}</div></article><article className="panel quick-panel"><header><div><h3>Quick actions</h3><p>Common tasks, one click away</p></div></header><div className="quick-grid"><Link href="/portal/invitations"><span className="blue">＋</span><strong>Invite visitor</strong><small>Create a secure pass</small></Link><Link href="/portal/entry-exit"><span className="orange">⌁</span><strong>Scan pass</strong><small>Verify QR or PIN</small></Link><Link href="/portal/pickup"><span className="aqua">✓</span><strong>Authorize pickup</strong><small>Assign a pickup person</small></Link><Link href="/portal/students"><span className="violet">♙</span><strong>Add student</strong><small>Create student record</small></Link></div></article></section>
        <section className="module-grid"><article className="module-card vas"><div><small>VISITOR AUTHORIZATION</small><h3>VAS</h3><p>Manage invitations, entries, and visitor passes from one secure workspace.</p><div><span><b>24</b> today</span><span><b>8</b> active</span><span><b>3</b> gates</span></div><Link href="/portal/visitors">Open VAS <b>→</b></Link></div><span className="module-orbit">◎</span></article><article className="module-card pas"><div><small>PICK-UP AUTHORIZATION</small><h3>PAS</h3><p>Keep student release safe with verified people and time-bound authorizations.</p><div><span><b>17</b> today</span><span><b>3</b> pending</span><span><b>486</b> students</span></div><Link href="/portal/pickup">Open PAS <b>→</b></Link></div><span className="module-orbit">⌁</span></article></section>
    </AuthenticatedLayout>;
}
