import { PageProps } from '@/types';
import { Head, Link } from '@inertiajs/react';

const modules=[{code:'VAS',href:'visitors',title:'Visitor authorization',text:'Invite guests, issue time-bound QR passes, verify identity, and track entry and exit.',color:'blue',icon:'↗'},{code:'PAS',href:'pickup',title:'Pickup authorization',text:'Protect every student release with approved people, secure PINs, and accountable handovers.',color:'orange',icon:'✓'},{code:'VTS',href:'vts',title:'Vehicle tracking',text:'Monitor fleet locations, driver status, device health, speed, and telemetry in real time.',color:'aqua',icon:'⌖'},{code:'PBS',href:'pbs',title:'Panic & emergency',text:'Activate critical alerts, coordinate responders, and maintain a complete incident timeline.',color:'violet',icon:'!'}];
export default function Welcome({auth}:PageProps){return <><Head title="Secure every move"/><div className="landing"><nav className="landing-nav"><Link href="/" className="brand"><span className="brand-mark">N</span><span>NEMTRACK<small>SECURE EVERY MOVE</small></span></Link><div className="landing-links"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#security">Security</a></div><div className="landing-auth">{auth.user?<Link className="landing-primary" href="/dashboard">Open dashboard →</Link>:<><Link href="/login">Sign in</Link><Link className="landing-primary" href="/register">Get started →</Link></>}</div></nav>
<main><section className="hero"><div className="hero-copy"><span className="eyebrow"><i/> ONE PLATFORM. EVERY MOVEMENT SECURE.</span><h1>Safety that moves<br/><em>with your world.</em></h1><p>NEMTRACK unifies visitor access, student pickup, vehicle intelligence, and emergency response—so your organization always knows who is moving, where, and why.</p><div className="hero-actions"><Link href={auth.user?'/dashboard':'/register'}>Start securing today →</Link><a href="#platform">Explore the platform</a></div><div className="trust-row"><span><b>✓</b> Multi-tenant security</span><span><b>✓</b> Real-time audit trails</span><span><b>✓</b> Mobile-first control</span></div></div>
<div className="hero-console"><div className="console-top"><span><i/> Greenfield Academy</span><b>LIVE</b></div><div className="console-main"><div className="console-greeting"><span>COMMAND CENTRE</span><h3>Everything is secure.</h3><p>4 modules protecting your organization</p></div><div className="console-stats"><div><span className="blue">↗</span><b>24</b><small>Visitors</small></div><div><span className="orange">✓</span><b>17</b><small>Pickups</small></div><div><span className="aqua">⌖</span><b>8</b><small>Vehicles</small></div></div><div className="console-event"><span>✓</span><div><b>Visitor verified</b><small>Ada Mensah · Main Gate · now</small></div><em>Granted</em></div><div className="console-event"><span className="orange">!</span><div><b>Bus 04 arrived safely</b><small>North Campus · 2 min ago</small></div><em>Tracked</em></div></div></div></section>
<section className="proof"><span>BUILT FOR ORGANIZATIONS THAT PROTECT PEOPLE</span><div><b>Schools</b><b>Estates</b><b>Hospitals</b><b>Corporations</b><b>Government</b><b>Events</b></div></section>
<section id="platform" className="platform-section"><div className="section-heading"><span>THE NEMTRACK PLATFORM</span><h2>Four systems. One source of truth.</h2><p>Activate only what you need today. Add more protection as your organization grows.</p></div><div className="landing-modules">{modules.map(m=><article key={m.code}><span className={`module-symbol ${m.color}`}>{m.icon}</span><small>{m.code}</small><h3>{m.title}</h3><p>{m.text}</p><Link href={auth.user?`/portal/${m.href}`:'/register'}>Explore {m.code} →</Link></article>)}</div></section>
<section id="solutions" className="workflow-section"><div><span className="eyebrow">FROM REQUEST TO SAFE ARRIVAL</span><h2>Every critical journey is verified.</h2><p>Replace paper logs, phone calls, and uncertain handovers with secure workflows that keep people informed and accountable.</p></div><ol><li><b>01</b><span><strong>Authorize</strong><small>A trusted user creates a secure, time-bound permission.</small></span></li><li><b>02</b><span><strong>Verify</strong><small>Security confirms QR, PIN, identity, device, and access rules.</small></span></li><li><b>03</b><span><strong>Track</strong><small>Every movement and decision becomes part of the live record.</small></span></li><li><b>04</b><span><strong>Respond</strong><small>Teams receive immediate context when safety needs attention.</small></span></li></ol></section>
<section id="security" className="security-section"><div><span>SECURITY BY DESIGN</span><h2>Built for decisions that affect real people.</h2></div><div><p>Tenant-isolated data</p><p>Permission-based access</p><p>Expiring & revocable passes</p><p>Immutable audit trails</p><p>Encrypted API authentication</p><p>Server-side verification</p></div></section>
<section className="landing-cta"><span>READY TO SECURE EVERY MOVE?</span><h2>Bring clarity to every gate,<br/>pickup, vehicle, and emergency.</h2><Link href={auth.user?'/dashboard':'/register'}>Launch NEMTRACK →</Link></section></main><footer className="landing-footer"><div className="brand"><span className="brand-mark">N</span><span>NEMTRACK<small>SECURE EVERY MOVE</small></span></div><p>© 2026 NEMTEK. Secure mobility and access infrastructure.</p></footer></div></>}
