import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import InputError from '@/Components/InputError';
import { PageProps } from '@/types';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

export default function Edit({ status }: PageProps<{ mustVerifyEmail: boolean; status?: string }>) {
    const user = usePage<PageProps>().props.auth.user;
    const [deleteOpen, setDeleteOpen] = useState(false);
    const profile = useForm({ name: user.name, email: user.email });
    const password = useForm({ current_password: '', password: '', password_confirmation: '' });
    const removal = useForm({ password: '' });
    const initials = user.name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();
    const saveProfile = (e: FormEvent) => { e.preventDefault(); profile.patch(route('profile.update'), { preserveScroll: true }); };
    const savePassword = (e: FormEvent) => { e.preventDefault(); password.put(route('password.update'), { preserveScroll: true, onSuccess: () => password.reset() }); };
    const deleteAccount = (e: FormEvent) => { e.preventDefault(); removal.delete(route('profile.destroy')); };

    return <AuthenticatedLayout><Head title="Profile & security" />
        <section className="profile-heading"><div><span>ACCOUNT CENTRE</span><h1>Profile & security</h1><p>Manage your identity, sign-in credentials, and NEMTRACK account.</p></div><Link href={route('logout')} method="post" as="button" className="profile-logout">↪ Sign out of NEMTRACK</Link></section>
        {status && <div className="profile-notice">✓ {status}</div>}
        <section className="profile-grid">
            <aside className="identity-card"><div className="identity-cover"><i /><i /><i /></div><div className="identity-body"><span className="large-avatar">{initials}</span><h2>{user.name}</h2><p>{user.email}</p><span className="role-pill">{user.role?.replaceAll('_', ' ') ?? 'Organization administrator'}</span><div className="identity-meta"><div><span>ORGANIZATION</span><b>{user.organization?.name ?? 'NEMTRACK'}</b></div><div><span>ACCOUNT STATUS</span><b className="verified-dot">● {user.status ?? 'active'}</b></div><div><span>MEMBER ID</span><b>NMT-{String(user.id).padStart(5, '0')}</b></div></div></div><Link href="/dashboard">← Return to dashboard</Link></aside>
            <div className="profile-panels">
                <form className="settings-panel" onSubmit={saveProfile}><header><span className="settings-icon blue">♙</span><div><h3>Personal information</h3><p>Details used throughout your organization workspace.</p></div></header><div className="settings-content"><div className="profile-field-grid"><label>Full name<input value={profile.data.name} onChange={e => profile.setData('name', e.target.value)} required /><InputError message={profile.errors.name} /></label><label>Work email<input type="email" value={profile.data.email} onChange={e => profile.setData('email', e.target.value)} required /><InputError message={profile.errors.email} /></label></div><div className="read-only-row"><div><span>Role</span><b>{user.role?.replaceAll('_', ' ') ?? 'Administrator'}</b></div><div><span>Organization</span><b>{user.organization?.name ?? 'NEMTRACK'}</b></div></div></div><footer><span>{profile.recentlySuccessful ? '✓ Profile saved' : 'Changes update your platform identity.'}</span><button disabled={profile.processing}>Save changes</button></footer></form>
                <form className="settings-panel" onSubmit={savePassword}><header><span className="settings-icon orange">⌾</span><div><h3>Password & authentication</h3><p>Use a strong, unique password to protect physical access data.</p></div></header><div className="settings-content"><label>Current password<input type="password" value={password.data.current_password} onChange={e => password.setData('current_password', e.target.value)} placeholder="Enter current password" /><InputError message={password.errors.current_password} /></label><div className="profile-field-grid"><label>New password<input type="password" value={password.data.password} onChange={e => password.setData('password', e.target.value)} placeholder="At least 8 characters" /><InputError message={password.errors.password} /></label><label>Confirm new password<input type="password" value={password.data.password_confirmation} onChange={e => password.setData('password_confirmation', e.target.value)} placeholder="Repeat new password" /><InputError message={password.errors.password_confirmation} /></label></div><div className="security-tip"><span>◈</span><p><b>Security recommendation</b>Never reuse this password on another service.</p></div></div><footer><span>{password.recentlySuccessful ? '✓ Password updated' : 'Active sessions remain monitored.'}</span><button disabled={password.processing}>Update password</button></footer></form>
                <section className="settings-panel danger-panel"><header><span className="settings-icon red">!</span><div><h3>Account controls</h3><p>Sign out safely or permanently remove your account.</p></div></header><div className="account-actions"><div><span><b>End your current session</b><small>You’ll need your credentials to access NEMTRACK again.</small></span><Link href={route('logout')} method="post" as="button">Log out</Link></div><div><span><b>Delete account</b><small>This permanently removes your user record and cannot be undone.</small></span><button onClick={() => setDeleteOpen(true)}>Delete account</button></div></div></section>
            </div>
        </section>
        {deleteOpen && <div className="modal-backdrop" onMouseDown={() => setDeleteOpen(false)}><form className="portal-modal delete-modal" onSubmit={deleteAccount} onMouseDown={e => e.stopPropagation()}><header><div><span>DANGER ZONE</span><h2>Delete your account?</h2></div><button type="button" onClick={() => setDeleteOpen(false)}>×</button></header><div className="delete-warning"><span>!</span><p><b>This action is permanent.</b>Your profile and access to this workspace will be removed. Enter your password to confirm.</p></div><label>Current password<input type="password" autoFocus value={removal.data.password} onChange={e => removal.setData('password', e.target.value)} placeholder="Enter your password" /><InputError message={removal.errors.password} /></label><footer><button type="button" className="btn-secondary" onClick={() => setDeleteOpen(false)}>Keep account</button><button className="danger-action" disabled={removal.processing}>Delete permanently</button></footer></form></div>}
    </AuthenticatedLayout>;
}
